source 'https://github.com/CocoaPods/Specs.git'

target 'NavigationMenuController', :exclusive => true do
  pod "NavigationMenuController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NavigationMenuController", :path => "../"

  
end
